# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acreage', models.FloatField(null=True)),
                ('building_year', models.SmallIntegerField(null=True)),
                ('city_code', models.CharField(max_length=20, null=True)),
                ('decoration', models.CharField(max_length=20, null=True)),
                ('district_name', models.CharField(max_length=20, null=True)),
                ('face', models.CharField(max_length=20, null=True)),
                ('floor_state', models.CharField(max_length=50, null=True)),
                ('house_rent_id', models.IntegerField(null=True)),
                ('house_type', models.CharField(max_length=20, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('lift_scale', models.CharField(max_length=20, null=True)),
                ('look_count', models.IntegerField(null=True)),
                ('metro_remark', models.CharField(max_length=100, null=True)),
                ('online_time', models.DateTimeField(null=True)),
                ('plate_id', models.IntegerField(null=True)),
                ('plate_name', models.CharField(max_length=50, null=True)),
                ('private_bathroom', models.IntegerField(null=True)),
                ('property_name', models.CharField(max_length=50, null=True)),
                ('property_no', models.IntegerField(null=True)),
                ('rent_price', models.FloatField(null=True)),
                ('rent_type', models.IntegerField(null=True)),
                ('room', models.IntegerField(null=True)),
                ('web_url', models.CharField(max_length=200, null=True)),
                ('tags', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
