# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='online_time',
        ),
        migrations.AddField(
            model_name='apartment',
            name='_online_time',
            field=models.DateTimeField(db_column='online_time', null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='house_rent_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
